spring:
  application:
    name: screensound
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
external:
  wikipedia:
    base-url: https://pt.wikipedia.org
    user-agent: screensound/1.0
